<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Buildora activation · Naxas</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="min-h-screen bg-slate-950 font-sans text-slate-900 antialiased">
<main class="relative flex min-h-screen items-center justify-center overflow-hidden px-4 py-12 sm:px-6">
    <div class="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_top_left,rgba(99,102,241,.22),transparent_35%),radial-gradient(circle_at_bottom_right,rgba(14,165,233,.14),transparent_35%)]"></div>
    <div class="relative w-full max-w-lg">
        <a href="{{ route('home') }}" class="mb-6 flex items-center justify-center gap-3 text-white">
            <span class="grid size-10 place-items-center rounded-xl bg-indigo-500 text-sm font-bold shadow-lg shadow-indigo-950">NX</span>
            <span class="text-lg font-semibold">Naxas License Portal</span>
        </a>

        <section class="rounded-3xl border border-white/10 bg-white p-6 shadow-2xl shadow-black/30 sm:p-8">
            <div class="mb-7">
                <p class="mb-2 text-xs font-bold uppercase tracking-[0.18em] text-indigo-600">Secure license verification</p>
                <h1 class="text-2xl font-bold tracking-tight text-slate-950 sm:text-3xl">Buildora activation</h1>
                <p class="mt-2 text-sm leading-6 text-slate-500">Enter the request token generated by Buildora and confirm the installation domain.</p>
            </div>

            @isset($lookupError)
                <div class="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800" role="alert">{{ $lookupError }}</div>
            @endisset
            @if($errors->any())
                <div class="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800" role="alert">{{ $errors->first() }}</div>
            @endif

            @isset($activation)
                @php
                    $statusStyles = ['pending' => 'border-amber-200 bg-amber-50 text-amber-800', 'approved' => 'border-emerald-200 bg-emerald-50 text-emerald-800', 'completed' => 'border-emerald-200 bg-emerald-50 text-emerald-800', 'rejected' => 'border-red-200 bg-red-50 text-red-800', 'expired' => 'border-slate-200 bg-slate-50 text-slate-700'];
                @endphp
                <div class="mb-6 rounded-xl border p-4 {{ $statusStyles[$activation->status] ?? 'border-slate-200 bg-slate-50 text-slate-700' }}">
                    <div class="flex items-center justify-between gap-4"><span class="text-sm font-semibold">Activation status</span><span class="rounded-full bg-white/70 px-2.5 py-1 text-xs font-bold uppercase tracking-wide">{{ ucfirst($activation->status) }}</span></div>
                    <p class="mt-2 text-sm">Domain: <strong>{{ $activation->normalized_domain }}</strong></p>
                    @if($activation->status === 'pending')<p class="mt-1 text-sm">Your request is awaiting administrator review.</p>
                    @elseif($activation->status === 'approved')<p class="mt-1 text-sm">Return to Buildora to securely retrieve the license.</p>
                    @elseif($activation->status === 'completed')<p class="mt-1 text-sm">This installation has received its license.</p>
                    @elseif($activation->status === 'rejected')<p class="mt-1 text-sm">{{ $activation->safe_failure_message }}</p>
                    @elseif($activation->status === 'expired')<p class="mt-1 text-sm">This request has expired. Generate a new request from Buildora.</p>@endif
                </div>
            @endisset

            <form method="POST" class="space-y-5">
                @csrf
                <label class="grid gap-2 text-sm font-semibold text-slate-700">Activation request token
                    <input class="w-full rounded-xl border border-slate-300 bg-white px-4 py-3 font-mono text-sm font-normal uppercase outline-none transition placeholder:normal-case placeholder:text-slate-400 focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100" name="request_token" required autocomplete="off" spellcheck="false" placeholder="BRQ-XXXX-XXXX-XXXX">
                </label>
                <label class="grid gap-2 text-sm font-semibold text-slate-700">Domain confirmation
                    <input class="w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm font-normal outline-none transition placeholder:text-slate-400 focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100" name="domain" value="{{ old('domain') }}" required autocomplete="url" placeholder="example.com">
                </label>
                <button class="flex w-full items-center justify-center rounded-xl bg-indigo-600 px-4 py-3 text-sm font-semibold text-white shadow-sm transition hover:bg-indigo-500 focus:outline-none focus:ring-4 focus:ring-indigo-200">Check activation status</button>
            </form>

            <div class="mt-6 flex items-start gap-3 border-t border-slate-100 pt-5 text-xs leading-5 text-slate-500">
                <svg class="mt-0.5 size-4 shrink-0 text-slate-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/><path d="m9 12 2 2 4-4"/></svg>
                <p>The token is verified securely and is never displayed after submission.</p>
            </div>
        </section>
        <p class="mt-6 text-center text-xs text-slate-500">© {{ date('Y') }} Naxas Limited</p>
    </div>
</main>
</body>
</html>
