@extends('admin.layout')
@section('title', 'Activation Requests')
@section('content')
<div class="mb-7"><h1 class="text-2xl font-bold tracking-tight sm:text-3xl">Activation requests</h1><p class="mt-1 text-sm text-slate-500">Review and assign licenses to installation requests.</p></div>
<section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
    @if($requests->isEmpty())<div class="p-12 text-center text-sm text-slate-500">No activation requests found.</div>@else
    <div class="max-w-full overflow-x-auto"><table class="min-w-[1050px] w-full text-left text-sm">
        <thead class="border-b border-slate-200 bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3 font-semibold">Request</th><th class="px-5 py-3 font-semibold">Product</th><th class="px-5 py-3 font-semibold">Domain</th><th class="px-5 py-3 font-semibold">Installation</th><th class="px-5 py-3 font-semibold">Environment</th><th class="px-5 py-3 font-semibold">Requested</th><th class="px-5 py-3 font-semibold">Status</th><th></th></tr></thead>
        <tbody class="divide-y divide-slate-100">@foreach($requests as $request)<tr class="hover:bg-slate-50/70"><td class="px-5 py-4 font-mono text-xs">{{ $request->request_token_prefix }}…</td><td class="px-5 py-4"><span class="font-medium">{{ $request->product->name }}</span><span class="block text-xs text-slate-500">{{ $request->edition->name }} · v{{ $request->application_version }}</span></td><td class="px-5 py-4 font-medium">{{ $request->normalized_domain }}</td><td class="max-w-48 truncate px-5 py-4 font-mono text-xs text-slate-500" title="{{ $request->installation_uuid }}">{{ $request->installation_uuid }}</td><td class="px-5 py-4 capitalize text-slate-600">{{ $request->environment }}</td><td class="px-5 py-4 text-slate-500">{{ $request->created_at->diffForHumans() }}<span class="block text-xs">Expires {{ $request->expires_at->format('M j, Y H:i') }}</span></td><td class="px-5 py-4"><span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold capitalize text-slate-700">{{ $request->status }}</span></td><td class="px-5 py-4 text-right"><a class="font-semibold text-indigo-600 hover:text-indigo-500" href="{{ route('admin.requests.show', $request) }}">Review</a></td></tr>@endforeach</tbody>
    </table></div><div class="border-t border-slate-200 px-5 py-4">{{ $requests->links() }}</div>@endif
</section>
@endsection
